### ISSUE TITLE
Usage of the plugin

### ISSUE THREAD

**Issue by namnamir** [NgoHuy/mailspring-keybase#2]
Hi,

It may be a basic question and not relevant to what you have done.

I was able to install the plugin successfully but there is no change in the client environment, I can't see any button related to PGP; neither on "preferences" or on "compose mail". Where can I find the plugin to be able to manage it as we as the keys?

**Comment by NgoHuy** [comment]
Hi,
You must edit ` ~/.config/Mailspring/config.json` then remove `keybase` from `disabledPackages` and restart mailspring

**Comment by mrdev023** [comment]
And on Mac OS X ?

**Comment by NgoHuy** [comment]
After searching github, I found `~/Library/Application Support/Mailspring`

**Comment by mrdev023** [comment]
File doesn't exist :/ i'l tried this also

**Comment by mrdev023** [comment]
> File doesn't exist :/ i'l tried this also

I found it ~/.local/Mailspring

**Comment by mrdev023** [comment]
It's not possible to Sign email ? I found one button to encrypt body

**Comment by NgoHuy** [comment]
yes, only encrypt it, hix

**Comment by valentt** [comment]
So far it seams to work in Fedora, I'll now add few keys and test it out. I'll follow up with full feedback. Thanks!

**Comment by fazlerabbi37** [comment]
Using Ubuntu 18.04, got the Encryption tab on Preference and was able to generate key pair but can't find any button to encrypt body in mail composer mention by @mrdev023. @mrdev023 would you be able to attach a screenshot for clarification?

**Comment by hag0r** [comment]
@valentt I wasn't able to make it work on my Fedora 29... any hints?

What I can see in the developer console is: 
```
Uncaught Error: Cannot find module 'prop-types'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/usr/share/mailspring/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (encrypt-button.jsx:26:1)
    at Object.<anonymous> (encrypt-button.jsx:240:1)
    at Module._compile (module.js:642:30)
    at Object.value [as .jsx] (/usr/share/mailspring/resources/app.asar/src/compile-cache.js:145:21)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (main.es6:3:1)
    at Object.<anonymous> (main.es6:34:2)
    at Module._compile (module.js:642:30)
    at Object.value [as .es6] (/usr/share/mailspring/resources/app.asar/src/compile-cache.js:145:21)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Package.activate (/src/package.es6:39:22)
    at PackageManager.activatePackage (/src/package-manager.es6:107:9)
    at setTimeout (/src/package-manager.es6:74:14)
```
Not sure however, if that is related to the plugin...

**Comment by NgoHuy** [comment]
@sthagedorn you must change to keybase plugin's folder and run `npm install` to make dependencies installed

**Comment by hag0r** [comment]
Ah yeah that did the trick. Thanks!

My steps were:

0. stop all Mailspring processes
1. clone repository into any location
2. `cd /path/to/mailspring-keybase` and then `npm install`
3. start Mailspring and add plugin - you should see a success notification
4. close Mailspring and edit `config.json` and remove `keybase` from disabled plugins list
5. start Mailspring, key management can be found in preferences 

I will try it now. :)

**Comment by dirkdavidis** [comment]
@sthagedorn maybe i am blind ...
where to clone the repo?
i done all steps but i cant see the management in preferences on fedora29 maybe u can assist

**Comment by hag0r** [comment]
@dirkdavidis I updated my comment. HTH
