### ISSUE TITLE
Can't import keys.

### ISSUE THREAD

**Issue by Sving1024** [NgoHuy/mailspring-keybase#20]
First i want to thank you for providing such a useful plugin. But i have some trouble importing the key.
### what i did
1. Following the installation instructions, and Encryption tag appears in preferences。
2. Using command `gpg -a -o private.key --export-secret-keys <user-id>` to export private key.
3. `cat ./private.key`.
4. Press the 'Paste in a new key' button and paste the output in it and type in address and password
5. It says, invaid key body.
nothing appears in consle.

Also, I tried Import a key from file as well.i select the key and click import. But nothing happened without the 'paste you key here' input box appears.

beside, there are following output in consle:
```
TypeError: Cannot read properties of undefined (reading 'dialog')
    at PGPKeyStore._displayError (/home/Sving1024/.config/Mailspring/packages/keybase/lib/pgp-key-store.js:535:27)
    at /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:145:31
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1201:20
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1198:22
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1200:13
    at Deferrals.exports.Deferrals.Deferrals._call (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at trampoline (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1171:32
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1172:15
    at Function.KeyManager.import_from_armored_pgp (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1177:15)
    at /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:141:37
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {url: '/home/Sving1024/.config/Mailspring/packages/keybase/lib/pgp-key-store.js', line: 535, column: 27, pluginIds: Array(1)}
module.exports.ErrorLogger.reportError @ /usr/share/mailspring/resources/app.asar/src/error-logger.js:99
reportError @ app-env.ts:237
window.onerror @ app-env.ts:161
/home/Sving1024/.config/Mailspring/packages/keybase/lib/pgp-key-store.js:535 Uncaught TypeError: Cannot read properties of undefined (reading 'dialog')
    at PGPKeyStore._displayError (/home/Sving1024/.config/Mailspring/packages/keybase/lib/pgp-key-store.js:535:27)
    at /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:145:31
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1201:20
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1198:22
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1200:13
    at Deferrals.exports.Deferrals.Deferrals._call (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:98:26
    at trampoline (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:96:16)
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1171:32
    at /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1172:15
    at Function.KeyManager.import_from_armored_pgp (/home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1177:15)
    at /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:141:37
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
_displayError @ /home/Sving1024/.config/Mailspring/packages/keybase/lib/pgp-key-store.js:535
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:145
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1201
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1198
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1200
exports.Deferrals.Deferrals._call @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:86
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:98
trampoline @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:64
exports.Deferrals.Deferrals._fulfill @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/iced-runtime/lib/runtime.js:96
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1171
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1172
KeyManager.import_from_armored_pgp @ /home/Sving1024/.config/Mailspring/packages/keybase/node_modules/kbpgp/lib/openpgp/keymanager.js:1177
(anonymous) @ /home/Sving1024/.config/Mailspring/packages/keybase/lib/key-adder.js:141
readFileAfterClose @ node:internal/fs/read_file_context:68
```

### expected behavier
The key should be imported.

How to solve this?

**Comment by NgoHuy** [comment]
the repo is out date, please use another.
